## Numpy
Numpy是python的一个常用包,主要用来实现大型矩阵的运算

In [ ]:
# 导入numpy
import numpy as np

# 其他包
import time
import random

### Numpy的速度
为什么我们要使用numpy

In [3]:
# 用python的list实现矩阵,用多重循环实现矩阵乘法
def pure_python_matrix_multiply(A,B):
    m=len(A)
    j=len(A[0])
    k=len(B)
    n=len(B[0])
    if(j!=k):
        raise ValueError("第一个矩阵的列数不等于第二个矩阵的行数")
    C=[[0 for _ in range(n)] for _ in range(m)]
    for i in range(m):
        for v in range(n):
            for b in range(j):
                C[i][v]+=A[i][b]*B[b][v]
    return C

N=200
A=[[10*random.random() for _ in range(N)] for _ in range(N)]
B=[[10*random.random() for _ in range(N)] for _ in range(N)]
start_time=time.time()
C=pure_python_matrix_multiply(A,B)
# print(C)
print(f"耗时为{time.time()-start_time}")


耗时为2.002410650253296


In [4]:
a=np.array(A)
b=np.array(B)
start_time=time.time()
c=np.dot(a,b)
# print(c)
print(f"耗时为{time.time()-start_time}")

耗时为0.0518341064453125


### ndarray的创建

#### 按指定shape创建ndarray

In [5]:
# np.empty(shape, dtype = float, order = 'C'):创建未初始化的数组
# np.empty 方法用来创建一个指定形状（shape）,数据类型（dtype）且未初始化的数组
# order	数组在内存中的存储顺序,可选值为 'C'（按行优先）或 'F'（按列优先）,默认为 'K'（保留输入数组的存储顺序）
A = np.empty((3, 3), dtype=np.float64, order='C')
print(A)

# np.zeros(shape, dtype = float, order = 'C'):创建以0填充的数组
B = np.zeros((3, 3), dtype=np.int64, order='C')
print(B)

# np.ones(shape, dtype = float, order = 'C'):创建以1填充的数组
C = np.ones((3, 3), dtype=np.float64, order='C')
print(C)


# numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
# 用于创建一个与给定数组具有相同形状和相同数据格式的数组,数组元素以 0 来填充。
# a	给定要创建相同形状的数组
# dtype	创建的数组的数据类型
# order	数组在内存中的存储顺序,可选值为 'C'（按行优先）或 'F'（按列优先）,默认为 'K'（保留输入数组的存储顺序）
'''
subok	是否允许返回子类,如果为 True,则返回一个子类对象,否则返回一个与 a 数组具有相同数据类型和存储顺序的数组.
        比如numpy有子类matlib,子类的返回值是一个矩阵对象,如果将矩阵对象作为a输入
        如果subok为True,函数返回的也是矩阵对象
        如果subok为False,函数返回的对象是标准ndarray
'''
matrix = np.matrix([[1, 2], [3, 4]])
print(matrix)
print(type(matrix))
D = np.zeros_like(matrix, dtype=None, order='C', subok=True, shape=None)
print(type(D))
D = np.zeros_like(matrix, dtype=None, order='C', subok=False, shape=None)
print(type(D))
# shape	创建的数组的形状,如果不指定,则默认为 a 数组的形状。
# 这个参数一般不使用,因为使用zeros_like函数一般就是为了生成和a形状相同的ndarray,如果指定shape,那么只能保证数据类型与原数组相同,如果同时再指定dtype,直接去使用zeros就好了
D = np.zeros_like(matrix, dtype=None, order='C', subok=False, shape=(3, 3))
print(D.dtype)
print(matrix.dtype)
D = np.zeros_like(matrix, dtype=np.float64, order='C',
                  subok=False, shape=(3, 3))
print("这样D和matrix就完全没有关系了:")
print(D)
print(D.dtype)
print(matrix.dtype)

# numpy.ones_like(a, dtype=None, order='C', subok=True, shape=None)
# numpy.empty_like(a, dtype=None, order='C', subok=True, shape=None)
# 这两个函数的参数和zeros_like相同
E = np.ones_like(matrix, dtype=None, order='C', subok=False, shape=None)
F = np.empty_like(matrix, dtype=None, order='C', subok=False, shape=None)
print(E)
print(F)

[[4.67296746e-307 1.69121096e-306 1.11257937e-307]
 [1.89146896e-307 7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
int32
int32
这样D和matrix就完全没有关系了:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
int32
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]


#### 从数据范围生成ndarray

In [6]:
'''
numpy.arange(start, stop, step, dtype)
根据 start 与 stop 指定的范围以及 step 设定的步长,生成一个一维ndarray.
start	起始值,默认为0
stop	终止值（不包含）
step	步长,默认为1
dtype	返回ndarray的数据类型,如果没有提供,则会使用输入数据的类型。
'''
A=np.arange(1,100,2,np.float64)
print(A)

'''
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
start	序列的起始值
stop	序列的终止值,如果endpoint为true,该值包含于数列中
num	要生成的等步长的样本数量,默认为50
endpoint	该值为 true 时,数列中包含stop值,反之不包含,默认是True。
retstep	如果为 True 时,生成的数组中会显示间距,反之不显示。
dtype	ndarray 的数据类型
'''

B=np.linspace(0,100,30,endpoint=False,retstep=False,dtype=np.float64)
print(B)
print(B.size)
B=np.linspace(0,100,30,endpoint=True,retstep=False,dtype=np.float64)
print(B)
print(B.size)

'''
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
函数用于创建一个等比数列
start	    序列的起始值为:base ** start
stop	    序列的终止值为:base ** stop。如果endpoint为true,该值包含于数列中
num	        要生成的等步长的样本数量,默认为50
endpoint	该值为 true 时,数列中中包含stop值,反之不包含,默认是True。
base	    幂的基数
dtype	    ndarray 的数据类型
'''
#endpoint为False的话,类似于左闭右开区间,endpoint为True,类似于左右端点确定,再平均分配中间的数
#np.logspace(0, 10, num=10, endpoint=True, base=10, dtype=np.int64)比如这句,十个数字实际上吧1到10的幂指数平均分了9份,不是十份
C=np.logspace(0, 10, num=10, endpoint=False, base=10, dtype=np.int64)
print(C)
C=np.logspace(0, 10, num=10, endpoint=True, base=10, dtype=np.float64)
print(C)


[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49. 51. 53. 55. 57. 59. 61. 63. 65. 67. 69. 71.
 73. 75. 77. 79. 81. 83. 85. 87. 89. 91. 93. 95. 97. 99.]
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.         43.33333333 46.66666667 50.         53.33333333 56.66666667
 60.         63.33333333 66.66666667 70.         73.33333333 76.66666667
 80.         83.33333333 86.66666667 90.         93.33333333 96.66666667]
30
[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]
30
[         1         10     

#### 从已有序列转换ndarray

In [8]:
'''
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

object	数组或实现了__array__方法(NumPy库的一部分)的对象,或其他可迭代对象,如果输入对象是一个标量（即单个值,如数字或字符串）,那么返回的是一个0维数组,这个数组只包含那个标量值。
dtype	数组元素的数据类型
copy	对象是深拷贝还是浅拷贝,copy为True是深拷贝
order	数组在内存中的存储顺序,可选值为 'C'（按行优先）或 'F'（按列优先）,默认为 'K'（保留输入数组的存储顺序）
'''
# return  对非ndarray对象,返回一个复制数据新建的ndarray,如果object是ndarray对象,会深拷贝一个ndarray并返回

A = np.array([1, 2, 3])
# 使用 copy=True 创建一个新数组
B = np.array(A, copy=True)
# 使用 copy=False 创建一个新数组
C = np.array(A, copy=False)
A[0] = 999
print(B)
print(C)
# order	创建数组的样式,C为行方向,F为列方向,A为默认方法
# subok	默认返回一个与基类类型一致的数组
# ndmin	指定生成数组的最小维度
D = np.array([1, 2, 3], ndmin=3)
print(D)


'''
numpy.asarray(a, dtype=None, order=None, *, device=None, copy=None, like=None)
a   输入数据,采用可转换为数组的任何形式。这包括列表、元组列表、元组、元组的元组组、列表的元组和 ndarray.
dtype	数组元素的数据类型
copy	对象是深拷贝还是浅拷贝,copy为True是深拷贝,默认为None,表示仅在必要情况下复制数据,比如如果a是ndarray,则浅拷贝
like    通常用于创建与给定参考对象相似的新数组.
        例如,如果你有一个CuPy数组(CuPy是一个支持GPU加速的数组库),并希望使用NumPy函数创建一个与之兼容的新数组,
        你可以将CuPy数组传递给like参数,从而确保新数组也是CuPy数组而不是NumPy数组.
'''

# asanyarray()的特殊之处是支持np的各种子类,可以返回如matrix子类等子类,asanyarray和asarray一样,非必要不深拷贝
'''
numpy.asanyarray(a, dtype=None, order=None, *,like=None)
a   输入数据,采用可转换为数组的任何形式。这包括列表、元组列表、元组、元组的元组组、列表的元组和 ndarray.
dtype	数组元素的数据类型
like    通常用于创建与给定参考对象相似的新数组.
        例如,如果你有一个CuPy数组(CuPy是一个支持GPU加速的数组库),并希望使用NumPy函数创建一个与之兼容的新数组,
        你可以将CuPy数组传递给like参数,从而确保新数组也是CuPy数组而不是NumPy数组.
'''
# 对比三个函数拷贝的不同
a = np.array([1, 2])
b = np.array(a)
c = np.asarray(a)
d = np.asanyarray(a)
a[0] = 2
print(b)
print(c)
print(d)

[1 2 3]
[999   2   3]
[[[1 2 3]]]
[1 2]
[2 2]
[2 2]


### 索引和访问

#### 常用索引和切片

In [41]:
# 一维数组的索引和切片和Python的list切片一样

# 多维数组的索引和多维list一样，切片分维度切，每个维度和一维list切片一样，各维度之间用逗号分割
# 多维list不支持多维切片，只能用列表推导式
A=np.arange(1,1001)
A=A.reshape(10,10,10)
#单个元素索引
B=A[3][3][3]
print(B)
C=A[1:3,3:5,4:6]
print(C)
#切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。
D=C[...,0,0]
print(D)


334
[[[135 136]
  [145 146]]

 [[235 236]
  [245 246]]]
[135 235]


#### 高级索引

In [51]:
# 整数数组索引

# 整数数组索引是指使用一个数组C来访问另一个数组A的元素，这个数组中的每个元素都是目标数组中某个维度上的索引值。
# C的每个子数组的第i个元素，组合起来就是对A某一个元素的索引
A = np.array([[1,  2],  [3,  4],  [5,  6]]) 
B = A[[0,1,2],  [0,1,0]]  
print (B)
print("------------------------------")


# 布尔索引
# 我们可以通过一个布尔数组来索引目标数组。

import numpy as np 
 
X = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print (X)
print(X>5)
print (X[X >  5])
print("------------------------------")


# 花式索引--像一种不是很完备的整数索引
# 花式索引根据索引数组的值作为目标数组的某个轴的下标来取值

x=np.arange(27).reshape((3,3,3))
print(x)
print(x[[0,1],[0,2]])

[1 4 5]
------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]
------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 0  1  2]
 [15 16 17]]


### 常用属性

In [27]:
# ndarray的属性
X = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print('numpy_ndarray: ',X)
print('shape: ', X.shape)  # 形状
print('ndim: ', X.ndim)  # 维数
print('size: ', X.size)  # 元素个数
print('dtype: ', X.dtype)  # 元素类型
print('flags: ', X.flags)  # 数组内存信息
# ndarray.itemsize：返回数组储存的数据类型所占字节数。
# ndarray.nbytes：返回该数组占用的储存空间的总字节数。
# ndarray.T：返回该数组的转置。
# ndarray.real：返回该数组中每个元素的实部。
# ndarray.imag：返回该数组中每个元素的虚部。


numpy_ndarray:  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
shape:  (4, 3)
ndim:  2
size:  12
dtype:  int32
flags:    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### ndarray的运算

In [25]:
# 四则运算 四则运算是ndarray各个元素之间的运算,如果各ndarray之间的形状不同，会进行广播
A = np.array([[1, 2], [3, 4]])  # 定义一个2x2的矩阵 
B = np.array([[5, 6], [7, 8]])  # 定义一个2x2的矩阵
print(A + B)  # 矩阵加法
print(A - B)  # 矩阵减法
print(A * B)  # 矩阵乘法
print(A / B)  # 矩阵除法
print('----------------')
# ><等比较运算
# 比较运算符返回一个和原数组形状相同的bool数组，依次比较各元素，返回True或False
print(A > B)  # 矩阵比较
print(A <= 3)  # 矩阵比较
print('----------------')


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----------------
[[False False]
 [False False]]
[[ True  True]
 [ True False]]
----------------


In [26]:
# 广播机制 将各维度数据比较少的数据进行扩展，使得各维度数据相同，然后进行运算
C = np.array([[1], [3]])  # 定义一个2x1的矩阵
D = np.array([[5, 6]])  # 定义一个1x2的矩阵
print(A + B)  # 矩阵加法
arr1 = np.arange(30).reshape((1, 3, 2, 1, 5))
arr2 = np.arange(90).reshape((6, 3, 1, 5, 1))
print('arr1.shape', arr1.shape)
print('arr2.shape', arr2.shape)
res = arr1 + arr2
print(res.shape)
print('----------------')
#矩阵乘法 两种方法等价
print(np.dot(A, B))
print(A @ B)
print('----------------')
#矩阵转置
print(A.T)
print(A.transpose())
print('----------------')
#乘方和开方
print(A ** 2) # 乘方
print(np.sqrt(A)) # 开方

[[ 6  8]
 [10 12]]
arr1.shape (1, 3, 2, 1, 5)
arr2.shape (6, 3, 1, 5, 1)
(6, 3, 2, 5, 5)
----------------
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
----------------
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
----------------
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
# 三角函数运算
# 1. 基础三角函数
# numpy.sin(x): 计算数组 x 中每个元素的正弦值，输入的 x 是弧度制。
# numpy.cos(x): 计算数组 x 中每个元素的余弦值，输入的 x 是弧度制。
# numpy.tan(x): 计算数组 x 中每个元素的正切值，输入的 x 是弧度制。
# 2. 反三角函数
# numpy.arcsin(x): 计算数组 x 中每个元素的反正弦值，返回的值是弧度。
# numpy.arccos(x): 计算数组 x 中每个元素的反余弦值，返回的值是弧度。
# numpy.arctan(x): 计算数组 x 中每个元素的反正切值，返回的值是弧度。
# numpy.arctan2(y, x): 计算 y/x 的反正切值，考虑到 x 和 y 的符号，返回的值是弧度，用于确定点 (x, y) 的方位角。
# 3. 双曲三角函数
# numpy.sinh(x): 计算数组 x 中每个元素的双曲正弦值。
# numpy.cosh(x): 计算数组 x 中每个元素的双曲余弦值。
# numpy.tanh(x): 计算数组 x 中每个元素的双曲正切值。
# 4. 反双曲三角函数
# numpy.arcsinh(x): 计算数组 x 中每个元素的反双曲正弦值。
# numpy.arccosh(x): 计算数组 x 中每个元素的反双曲余弦值。
# numpy.arctanh(x): 计算数组 x 中每个元素的反双曲正切值。
# 5. 角度转换
# numpy.deg2rad(x): 将角度 x 从度数转换为弧度。
# numpy.rad2deg(x): 将角度 x 从弧度转换为度数。
# 6. 特殊三角函数
# numpy.hypot(x, y): 计算欧几里得范数 sqrt(x**2 + y**2)，即直角三角形的斜边长度。

# 基本三角函数
x = np.array([0, np.pi / 2, np.pi])
print(np.sin(x))  # [0. 1. 0.]
print(np.cos(x))  # [ 1. 0. -1.]
print(np.tan(x))  # [ 0. 1.63312394e+16 0.]

# 反三角函数
y = np.array([0, 1, -1])
print(np.arcsin(y))  # [ 0.          1.57079633 -1.57079633]
print(np.arccos(y))  # [1.57079633 0.         3.14159265]
print(np.arctan(y))  # [ 0.          0.78539816 -0.78539816]

# 角度转换
print(np.deg2rad(180))  # 3.141592653589793
print(np.rad2deg(np.pi))  # 180.0

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[ 0.          1.57079633 -1.57079633]
[1.57079633 0.         3.14159265]
[ 0.          0.78539816 -0.78539816]
3.141592653589793
180.0


In [ ]:
# 统计方法

# 范数
vec = np.array([3, 4])
print(np.linalg.norm(vec, ord=1))	# L1
print(np.linalg.norm(vec))			  # L2
print(np.linalg.norm(vec, ord=3))	# L3

#相关性分析
print(np.corrcoef(A, B)) # 皮尔逊系数矩阵
print(np.cov(A, B))	# 协方差矩阵

# 常用的统计值
arr = np.arange(0, 10)

# 最值
print(arr.min())
print(arr.max())

# 中位数
print(np.median(arr))

# 四分位点
Q1 = np.percentile(arr, 25)
Q1 = np.percentile(arr, 50)
Q1 = np.percentile(arr, 75)

# 求和/均值
print(arr.sum())
print(arr.mean())

# 标准差/方差
print(arr.std())
print(arr.var())

7.0
5.0
4.497941445275415
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.array([-1, 1, 1, -1])
# ndarray的条件运算
# np.where(condition, x, y)
result = np.where(c > 0, a, b)	# 满足条件则取 x，否则取 y，所以 0 位是 False，取 b 的值，1 位是 True，取 a 的值
print(result)

print('c > 0', c > 0) # 返回一个布尔数组，比如 c > 0 返回 [False  True  True False]
# np.select(conditions, choices, default=0) 
# conditions：条件列表。
# choices：每个条件对应的值列表。
# default：当所有条件都不满足时返回的默认值（可选）。
conditions = [a < 2, a > 2]
choices = [a * 10, a * 100]
# 当 a < 2 时，返回 a * 10，否则返回 a * 100
# 所以 [1, 2, 3, 4] -> [1 * 10, 2 * 100, 3 * 100, 4 * 100]
result = np.select(conditions, choices, default=0)
print(result)

[10  2  3 40]
c > 0 [False  True  True False]
[ 10   0 300 400]


### ndarray的形状操作和拼接

In [ ]:
#更改形状 reshape flatten 
nd_array = np.array([[1, 2, 3], [4, 5, 6]])

print("reshape: ")
print(nd_array)

new_nd_array = nd_array.reshape((3, 2)) # 改变数组形状
print(new_nd_array)

new_nd_array = new_nd_array.flatten()   # 将多维数组展开为一维
print(new_nd_array)

#数组的拼接
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(np.hstack([a, b])) # 水平拼接数组
print(np.vstack([a, b])) # 垂直拼接数组

# 按axis拼接
c = np.arange(81).reshape((3,3,3,3))
d = np.array(range(81)).reshape((3,3,3,3))

print('c.shape: ', c.shape)
print('d.shape: ', d.shape)
res0 = np.concatenate([c, d], axis=0)
res1 = np.concatenate([c, d], axis=1)
res2 = np.concatenate([c, d], axis=2)
res3 = np.concatenate([c, d], axis=3)
print('res0.shape: ', res0.shape)
print('res1.shape: ', res1.shape)
print('res2.shape: ', res2.shape)
print('res3.shape: ', res3.shape)

reshape: 
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[ 1  2  3  4 10 20 30 40]
[[ 1  2  3  4]
 [10 20 30 40]]
[ 1  2  3  4 10 20 30 40]
c.shape:  (3, 3, 3, 3)
d.shape:  (3, 3, 3, 3)
res0.shape:  (6, 3, 3, 3)
res1.shape:  (3, 6, 3, 3)
res2.shape:  (3, 3, 6, 3)
res3.shape:  (3, 3, 3, 6)


### 数值文件的读写

In [32]:
# 1. .npy文件的读写
# np.save()：将数组保存到 .npy 文件中。
# np.load()：从 .npy 文件中读取数组。

arr = np.array([1, 2, 3, 4, 5])
# 保存数组到文件
np.save('array_file.npy', arr)
# 从文件读取数组
loaded_arr = np.load('array_file.npy')
print(loaded_arr)  # 输出: [1 2 3 4 5]


# 2. .npz文件的读写
# np.savez()：将多个数组保存到一个 .npz 压缩文件中。
# np.load()：从 .npz 文件中读取数组。

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# 保存多个数组到一个压缩文件
np.savez('arrays_file.npz', array1=arr1, array2=arr2)
loaded = np.load('arrays_file.npz')
print(loaded['array1'])  # 输出: [1 2 3]
print(loaded['array2'])  # 输出: [4 5 6]

# 3. csv文件和txt文件的读写
# np.savetxt()：将数组保存为文本文件（如 .txt 或 .csv 格式）。
# np.loadtxt()：从文本文件中读取数组。

arr = np.array([[1.5, 2.3, 3.1], [4.7, 5.5, 6.8]])
# 保存数组到文本文件
np.savetxt('array_file.txt', arr, delimiter=',')

# 从文本文件读取数组
loaded_arr = np.loadtxt('array_file.txt', delimiter=',')
print(loaded_arr)

np.savetxt('array_file.csv', arr, delimiter=',')

# 从文本文件读取数组
loaded_arr = np.loadtxt('array_file.csv', delimiter=',')
print(loaded_arr)

[1 2 3 4 5]
[1 2 3]
[4 5 6]
[[1.5 2.3 3.1]
 [4.7 5.5 6.8]]
[[1.5 2.3 3.1]
 [4.7 5.5 6.8]]
